version: "3.8"

services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     - discovery.type=single-node

  # rabbitmq:
  #   image: rabbitmq:3.13-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    # depends_on:
    # - elasticsearch
    # - rabbitmq
    # environment:
    # - ELASTICSEARCH_HOST=http://elasticsearch:9200
    # - RABBITMQ_HOST=rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
